language: go
go:
- 1.13

jobs:
  include:
    - before_install: go build
      script:
        - go test -coverprofile coverage.out $(go list ./... | grep -v tests)
        - go tool cover -func=coverage.out
    - stage: style
      script:
        - ./.travis.gofmt.sh
        - ./.travis.govet.sh
        - ./.travis.golint.sh
        - ./.travis.gocyclo.sh

stages:
  - style
  - test
